version: '3'
services:
  postgres:
    image: postgres:15.5
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - java-spring-api

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - java-spring-api

networks:
  java-spring-api:
