version: '3'
services:
  postgres:
    image: postgres:15.5
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    ports:
      - "5432:5432"
    networks:
      - java-spring-api

  mongodb:
    image: mongo:4.4.26
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'changeme'
      MONGO_INITDB_DATABASE: 'api'
    networks:
      - java-spring-api

  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: 'root'
      ME_CONFIG_MONGODB_ADMINPASSWORD: 'changeme'
      ME_CONFIG_MONGODB_SERVER: 'mongodb'
    networks:
      - java-spring-api

  spring-app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - mongodb
    networks:
      - java-spring-api

networks:
  java-spring-api:
    name: java-spring-api
    driver: bridge
